<?php

namespace App\Admin\Repositories;

use App\Models\User as Model;
use Dcat\Admin\Grid;
use Dcat\Admin\Repositories\EloquentRepository;

class User extends EloquentRepository
{
    /**
     * Model.
     *
     * @var string
     */
    protected $eloquentClass = Model::class;

    public function get(Grid\Model $model)
    {
        return parent::get($model); // TODO: Change the autogenerated stub
    }

}
